### ISSUE TITLE
Allow plugin-specific JADE/HTML files

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#104]

**Comment by WuTheFWasThat** [comment]
ah, this makes sense.  although how would they specify where to have them included?  i think ideally, we would set up client-side templating.  for now, we have a virtual DOM so i think it makes most sense to add some hooks to that, though it's definitely a less pleasant experience than writing, say, jade templates

**Comment by za3k** [comment]
Agreed, closing this until we have some kind of concrete templating
