### ISSUE TITLE
cloning + save/load (import/export)

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#105]
doesnt have to be in first pass of aliasing, but we should make it work with save/load, so that the documents can be backed up properly

**Comment by za3k** [comment]
What happens now? I think the desired behavior in plaintext is to export, but lose information about being clones, for workflowy compatibility.

If we're going to change that, then we should label plaintext as (plaintext/workflowy-compatible) an JSON as (json/backup)

**Comment by WuTheFWasThat** [comment]
yep, i agree on desired behavior.  and yeah, i generally find yaml much better than json so i'm happy to make that switch

**Comment by za3k** [comment]
Wait, I'm unclear, are you saying plaintext/YAML should both exist and import/export slightly different data, or do you just want to keep the current system (lose information about clones with importing/exporting)

**Comment by WuTheFWasThat** [comment]
we talked about this already, but putting this here on github.  we'll should keep a json format to avoid breaking all existing tests.  so probably will just implement something with json in the end?

**Comment by za3k** [comment]
Paul reported that import is now using 40GB for him. This is probably because
1) export sizes are now bigger because of this bug
2) import/export is not done in a streaming way

So yeah, confirmed that this is causing actual issues.

**Comment by za3k** [comment]
Paul, can you mention that something is fixed/not while closing it? Thanks
