### ISSUE TITLE
fix inconsistent function signatures in data

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#108]
getChildren: Row -> [Row]
but
getParents: Row -> [ids]

Probably getChildren should be a method on the Row object, and data should just have functions with purely id-based functions?  there are a number of functions that take Rows but only use the id anyways

**Comment by za3k** [comment]
We could drop 'getParents' as a method on data, or call it @_getParents

I've been approximately trying to make data have only row-based functions exposed to the external world, so nothing outside the file 'data' should know about ids. I think this has made the code clearer, and for example adding cloning didn't affect almost anything outside the data.coffee file.

**Comment by WuTheFWasThat** [comment]
yeah, that makes sense.

Okay. so it was:

getChildren: Row -> [Row]
setChildren: id , [Row]
getParents: Row -> [ids]

and I've changed it to

getChildren: Row -> [Row]
setChildren: Row , [Row]
_getParents: id -> [ids]
_setParents: id, [ids]

it's asymmetric between children and parents, but that's not the end of the world and sorta makes sense, and is reflected in the names.
