### ISSUE TITLE
moveblock fixes

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#111]
The MoveBlock mutation should take care of the cursor.

also, it should not cause rowremoved and rowadded to get emitted

**Comment by za3k** [comment]
Not sure whether I agree about rowremoved and rowadded, it should probably emit something and that seems like it works for all current applications (imaginary version of marks as a plugin + time tracking)

**Comment by WuTheFWasThat** [comment]
i don't think you use it for time-tracking, and for marks it's more efficient when it's not emitted.  we could also emit a rowmoved, later, if we want

**Comment by za3k** [comment]
Oh, sorry, I misread as 'childRemoved' and 'childAdded'. Yeah, I agree these shouldn't be emitted.
