### ISSUE TITLE
move marks code out of core code

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#112]
make marks a plugin, possibly hidden

**Comment by za3k** [comment]
I think we should not have any hidden plugins.

**Comment by WuTheFWasThat** [comment]
yeah, fair.  i'm thinking now that it shouldn't be a plugin, but just use similar hooks to register things?

**Comment by za3k** [comment]
I think we should make it a visible plugin, that seems perfectly reasonable. And then if you don't want it to be disable-able, add it to CORE. (We can also make those say, display at the end and grayed out, to make it visually obvious they're internal components)

**Comment by WuTheFWasThat** [comment]
i'm fine with that too.  i'm also perfectly okay with allowing it to be disabled, actually.  but all the marks data will have to be wiped when that's done

**Comment by za3k** [comment]
Eurgh, I hadn't noticed issues around enabling and disabling plugins that maintain caches like that. Yeah, you could do something fancy to avoid wiping it, but just prompting the user "Really disable? This will delete all marks" is a lot easier and there's no reason to disable just the UI.
