### ISSUE TITLE
Trying to paste cloned row as sibling destroys clipboard

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#114]
Clone a row. Type dd on one instance of the row. Try to paste it as a sibling or descendant of its clone. Then try to paste it somewhere legal. Nothing happens.

A
> B[type dd here]
> C

B

result: changes into this...

A
> C

B[type p here]

result: warning, no change

A
> C[type p here]

B

result: no change or warning
expected: clone of B to appear underneath C.

**Comment by WuTheFWasThat** [comment]
couldn't reproduce - are you on master?

**Comment by paulfchristiano** [comment]
I'm not, I don't have the problem on master either.

I'm on time-tracking but reproduced with time tracking disabled, so I assumed it wasn't a problem with time tracking, but that was probably silly. Should I leave issues with time-tracking open here, or tag them somehow, or just close them?

**Comment by za3k** [comment]
Generally make sure to mention what branch/commit a bug refers to, even if it seems unimportant. It's a plus if you can test whether something you encounter happens on master as well.

If you know it only happens on time-tracking, also feel free to email me.

I'm going to leave this bug open until I fix it.

**Comment by WuTheFWasThat** [comment]
i pushed up a branch time-tracking rebased, so you should check if it happens there, first.  time-tracking is probably based off an old version of cloning

**Comment by za3k** [comment]
Can't reproduce, I think Jeff's guess (that time-tracking was using an old version of something) is correct.
