### ISSUE TITLE
Pressing enter at the end of a line splits unintuitively

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#115]
1. Edit a line ("The quick brown fox"). Let's say this line has id 777
2. Press enter at the end of the line.

The ID 777 is the new, empty line, rather than the original. It's more intuitive if it's the first line instead.

This is causing problems in time-tracking.

**Comment by WuTheFWasThat** [comment]
interesting.  good catch.  i could just change it to be the other way around, but then it would be unintuitive in the case where the cursor is at the beginning (certainly, the much less common case).  that's probably correct behavior though, right?

**Comment by za3k** [comment]
There's also cursor in the middle, where you want to have the second half have the new ID.
Cursor at the beginning -- eh yeah, let's just do the second half in all cases, that sounds most intuitive as a user to me.

Also check out the debug mode I re-added to master (this time as plugin so it's easier to turn on), which made this problem massively easier to debug. It just displays IDs for each row.

**Comment by WuTheFWasThat** [comment]
i remember now why i did it this way.  if the row has children, the child-parent relationships are preserved

**Comment by WuTheFWasThat** [comment]
maybe splitting something that has children should cause the second thing to be a child?

**Comment by za3k** [comment]
What workflowy does here, which seems sensible:
-If enter is at the beginning, insert a new node before
-If enter is in the middle, insert a new node before with the first half of the content
-If enter is at the end, insert a new node after (which if it has children, is the new first child)

**Comment by za3k** [comment]
Oh, and then it has some special rules for pressing enter on blank lines (which dedents rather than adding a new blank line). For the full procedure, check out the code of 'flowy', where I reverse-engineered all this stuff months ago.

**Comment by WuTheFWasThat** [comment]
ah k - yeah we could do that.  in what sense do workflowy "rows" have ids?

**Comment by za3k** [comment]
I'm not sure of all the details, but formatting is applied per-row-ID rather than per-character. If you e.g. strikethrough the line, it's really obvious how row identity works just by pressing Enter in various places.

**Comment by WuTheFWasThat** [comment]
11b3b04fe3eca1cc77f1ff51eb7e7f48e5ab1059
