### ISSUE TITLE
Make bitballoon automatically sync

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#116]
This should correspond to the latest version of master always, can you make this automatic?

**Comment by WuTheFWasThat** [comment]
i'd rather not, actually.  unless we move development to an off-master branch.  i'll update it right now though

**Comment by za3k** [comment]
The thing is that the documentation says "try <this code> out on bitballoon". If you're not going to make bitballoon sync, can you clarify the documentation so it's obvious it doesn't reflect the latest version?

I think a runner-up would be, can we embed a link to the git commit somewhere in the settings, so you can see the version bitballoon is running? I think that would also be useful if we end up adding some kind of debug reports eventually.

**Comment by WuTheFWasThat** [comment]
wont fix
