### ISSUE TITLE
Time tracking plugin: Display whether time tracking is on

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#117]
Add a display to the bottom bar, indicating if time-tracking is currently on or off, as long as the plugin is enabled.

**Comment by WuTheFWasThat** [comment]
@paulfchristiano do you ever use time tracking with the display off?  if not, i may just remove display toggling and close this issue

**Comment by paulfchristiano** [comment]
I never have used time tracking with the display off.

**Comment by WuTheFWasThat** [comment]
8e165caea6dbfd38816eb4be1c1656f0a69857d4
