### ISSUE TITLE
Time tracking plugin: Transfer time when a row is deleted

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#119]
If a row is deleted (all copies), its final parent should be allocated the time from the deleted row. This should be able to deal with lazy undo/redo.

**Comment by za3k** [comment]
Addressed in dfc9cf15dcca7d391e6e00dedfb5aa55d9c0dc84

**Comment by WuTheFWasThat** [comment]
this seems like weird behavior, in the case of delete->paste.  but yeah, it's not really obvious what to do

should this be closed?

**Comment by za3k** [comment]
Oh, I think delete -> paste is not handled correctly if 'delete' is now a cloning operation. Good catch.

**Comment by WuTheFWasThat** [comment]
this works now, https://github.com/WuTheFWasThat/vimflowy/commit/36b62ed886356fd4800b265b2615269c0e121acc
