### ISSUE TITLE
autosave to local disk

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#123]
for chrome app version, set up option for auto-saving to local disk (with configurable path and frequency)

**Comment by WuTheFWasThat** [comment]
related: #124

**Comment by za3k** [comment]
Is this technically possible without a browser extension? (Or with a browser extension, for that matter?)

**Comment by WuTheFWasThat** [comment]
it's not possible in the browser version, only the chrome app.  editing OP

**Comment by WuTheFWasThat** [comment]
chrome apps are no longer gonna be a thing

**Comment by WuTheFWasThat** [comment]
this is roughly possible now, since you can run a server writing to sqlite and have the browser talk to it
