### ISSUE TITLE
autosave to cloud

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#124]
support for saving vimflowy files to the cloud somewhere (such as google drive or a server with a database).  the data store api is synchronous, so for now probably just sync occasionally  (possibly user-triggered?) and show a little "Synced!" icon

related: #123
##

**Comment by vbatts** [comment]
+1

**Comment by gunar** [comment]
[remoteStorage.js](https://remotestorage.io/) would be a perfect mathch. It is an open protocol for per-user storage on the Web. Perfect for "unhosted" webapps.

It already has both [free and paid hosting services](https://wiki.remotestorage.io/Servers#Hosted).

**Comment by WuTheFWasThat** [comment]
@gunar that looks cool!  I'll look into it.  I was thinking options like firebase and https://horizon.io/ should be supported as well, which I assume is also possible

**Comment by gunar** [comment]
Totally. That's the beauty of it, it's a protocol. There are PHP, Frontend in JS and Node.js implementations. The app just requires access to the user's data, but the data is truly owned by the user (as opposed to being owned/hosted by Facebook's servers).

Disclaimer: I've helped out the project a while I go.

**Comment by WuTheFWasThat** [comment]
also related: https://github.com/WuTheFWasThat/vimflowy/issues/203

**Comment by WuTheFWasThat** [comment]
For those following this thread, it's now possible to use vimflowy backed by Firebase

**Comment by WuTheFWasThat** [comment]
closing in favor of https://github.com/WuTheFWasThat/vimflowy/issues/124

**Comment by gunar** [comment]
@WuTheFWasThat you've closed this issue in favor of itself!? :joy: :innocent:

**Comment by WuTheFWasThat** [comment]
whoops! #236

**Comment by thejeshgn** [comment]
couchdb would be interesting because it can sync.

**Comment by WuTheFWasThat** [comment]
@thejeshgn I'm not sure I understand.  do you mean replication?  for the key-value store api i'm using, I don't think any kind of conflict resolution strategy will work properly either, if that's what you mean

**Comment by gunar** [comment]
@WuTheFWasThat I think he means using PouchDB on the frontend and CouchDB on the back.
