### ISSUE TITLE
Consistency of goto mark behavior

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#125]
I'm interested in making macros that create and manipulate marks. (e.g. I I would like a macro to move the mark "head" to the current cursor). This would be much easier if goto mark just moved you straight to the location of the mark. (As is, any macro needs to do a ton of work in order to be robust to whether the mark has children and whether it is expanded.)

Even apart from this, I think I would very slightly prefer it if goto mark consistently zoomed to the mark's parent and put the cursor on the mark, rather than zooming into the mark if it has children. If needed, expanding the mark seems like it would add most of the value of the current functionality. Are there cases where this alternate behavior is much worse?

**Comment by WuTheFWasThat** [comment]
no, that behavior is probably better.  I'll change it
