### ISSUE TITLE
Saving macros?

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#126]
It would be nice if there were a way to save macros from one session to another, whether by saving the current values in localstorage, or by being able to write them to bullets, or by being able to write default values into the hotkeys file.

**Comment by za3k** [comment]
Would you want to be able to share macros across documents? Would you want to be able to have document-specific macros? Which one would you prefer as the default?

I think being able to bind hotkeys to persistent macros would be a pretty neat feature. You could record a macro, and then click "add new" in the hotkeys section of settings, maybe. Jeff, you might want to check out my re-bindable shortcuts UI in 'flowy'

**Comment by paulfchristiano** [comment]
I would mostly use document-specific macros.

**Comment by WuTheFWasThat** [comment]
this is pretty easy, i'll add it when i get a chance

**Comment by WuTheFWasThat** [comment]
binding hotkeys to macros would be cool, too, i agree.  it would actually make implementation of some of the actions easier, too... I already had this TODO in the code
```
  # TODO: something like this would be nice...
  # keyDefinitions.registerActionAsMacro CMD_DELETE_TO_HOME, [CMD_DELETE, CMD_HOME]
  keyDefinitions.registerAction [MODES.NORMAL, MODES.INSERT], CMD_DELETE_TO_HOME, {
   ... <ugly code follows>```

**Comment by WuTheFWasThat** [comment]
2de6b83e1f67c67c5d2cfc0c3cd956ecf63e2d4c, #132
