### ISSUE TITLE
Make data loss impossible

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#127]
Right now I don't recommend vimflowy to my friends because I think there's a reasonable chance they will lose their data somehow. This is the single biggest positive change vimflowy could make, for me.

One suggestion is, let's save backup versions of the data. If vimflowy encounters a fatal error and can't load the data and display it without issuing errors, roll back. This solution relates to #123 and #124. I think this isn't an amazing suggestion, got anything better?

Also, #96 will help I think.

**Comment by WuTheFWasThat** [comment]
it's already relatively unlikely that you actually lose data, due to the lack of garbage collection.  but yeah, the structure could get corrupt.  i don't see many options besides good testing, and backups.  (if we can't think of anything better than autosave, we should just close this, i think)

**Comment by za3k** [comment]
I don't mind closing the actual bug if it's unactionable, as long as that doesn't mean stop working on the problem. I do really think it's vimflowy's biggest issue right now--it's not unlikely to have your data corrupted. This has happened to Paul several times, although some of them using a development branch.

I'm suggesting multiple backups + rollback, which I think is relevantly different from a single auto-save.

**Comment by WuTheFWasThat** [comment]
fair enough, that isn't quite the same
