### ISSUE TITLE
making new documents

### ISSUE THREAD

**Issue by tsvibt** [WuTheFWasThat/vimflowy#137]
The "tips" bullet point says "Make many documents.  Just visit /documentname". I entered "https://vimflowy.bitballoon.com/test1" in my browser and got a 404.

**Comment by WuTheFWasThat** [comment]
sorry, i'll remove that bullet.  it only works when you run the local version

**Comment by za3k** [comment]
Why not make it work on bitballoon?

**Comment by WuTheFWasThat** [comment]
I dunno how to.  I haven't looked into it, though
