### ISSUE TITLE
easymotion

### ISSUE THREAD

**Issue by tsvibt** [WuTheFWasThat/vimflowy#138]
Hitting space doesn't seem to do anything. (I remapped some keys so it is possible I messed something up.)

**Comment by WuTheFWasThat** [comment]
if you go to settings -> plugins, is easy_motion turned on?

**Comment by tsvibt** [comment]
It wasn't, now it works great :)
(not clear from the tutorial that this is a plugin)

**Comment by WuTheFWasThat** [comment]
thanks for the feedback.  lemme know if you run into anything else!

**Comment by za3k** [comment]
Jeff, you know that I have a section of plugins which can be turned on by default, correct?

**Comment by WuTheFWasThat** [comment]
i know, and marks is on by default.  i wasn't sure if easy_motion should be, though.  my thinking was that vim has marks (though fairly different from vimflowy marks) but not easy motion (though it does have line numbers..)
