### ISSUE TITLE
[obscure] vimflowy intercepts keystrokes before some keymappings

### ISSUE THREAD

**Issue by tsvibt** [WuTheFWasThat/vimflowy#142]
[This may be more obscure than the trouble it is worth.] I use a custom keyboard layout that is a modified Colemak, to make it easier to type math like &+=-_^(){}[], e.g. alt+h is ^. But, vimflowy does not process this correctly; if I type alt+h in insert mode, nothing happens. For comparison, in order to remap vimflowy's keys, I had to type alt+c rather than ç, even though alt+c produces ç in my keyboard. This works now, but the replacements from my keyboard layout for other alt+ characters don't work. Either a way to make new keybindings for characters in insert modes, or having vimflowy accept the actual input from the modified keyboard layout, would work maybe. 
##

**Comment by WuTheFWasThat** [comment]
yep, i would like to eventually have a UI to set hotkeys which would accept the actual input, which i think would solve any issues you have

**Comment by tsvibt** [comment]
cool :)

**Comment by WuTheFWasThat** [comment]
@tsvibt does vimflowy only process things incorrectly when there are modifier keys?  

if you open the javascript console, you should see output when you type along these lines:

```
keycode 74 key meta+alt+j
bundle.js:3 Handling key: meta+alt+j
```

what happens when you type `alt+h`?

**Comment by tsvibt** [comment]
logger.coffee:36 keycode 72 key alt+h
logger.coffee:36 Handling key: alt+h
logger.coffee:36 Rendering:  true 134

**Comment by WuTheFWasThat** [comment]
interesting - in that case, I'm not sure I can distinguish between it and a regular `alt+h`.  What are you using to do the key mappings?

**Comment by tsvibt** [comment]
A custom keyboard layout, made with Ukelele: https://www.macupdate.com/app/mac/14495/ukelele

**Comment by WuTheFWasThat** [comment]
should be fixed if i ever get around to https://github.com/WuTheFWasThat/vimflowy/issues/179. if not, it's likely a wontfix
