### ISSUE TITLE
Time tracking plugin: Stuck on "enabling"

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#144]
The big problem here is that an error is getting throw during plugin initialization, and then it just shows "enabling" forever with no user feedback.

For this particular problem, looks like this is because cursor initialization was moved to 'init' in view. (and there are no plugin tests)

**Comment by WuTheFWasThat** [comment]
is this resolved?  FWIW, i cannot repro this bug

**Comment by WuTheFWasThat** [comment]
was fixed in d666b3bbdcc3120926c26002165e3ec714a0dfc4  and a40a3b6600bc3e0f9b0f26c058396472681042a1
