### ISSUE TITLE
Recovering from "inconsistent ids_to_marks"

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#146]
Something happened that caused mark ids to get messed up in my account, and I get "Inconsistent ids_to_marks" whenever I try to search marks. I have 53 marks, and one of the ids didn't match between the two dictionaries that it compares. I tried deleting that mark, but I still get the same error (now the mark isn't in one of the dictionaries and is in the other). 

I guess there are two bugs: whatever caused the marks to get messed up, and the fact that there is no way to recover from the error (even though the actual state of the document seems fine).

errorFactory/g@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:15918:22
exports.assert_deep_equals@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:15972:1
enableMarks/listMarks@http://bitballoon.scdn4.secure.raxcdn.com/bundles/7a3ea3c0d2b576395b888368ec6689703877b6c1.js:2:15257
enableMarks/</this.view.menu</</findMarks@http://bitballoon.scdn4.secure.raxcdn.com/bundles/7a3ea3c0d2b576395b888368ec6689703877b6c1.js:2:19262
enableMarks/</this.view.menu</<@http://bitballoon.scdn4.secure.raxcdn.com/bundles/7a3ea3c0d2b576395b888368ec6689703877b6c1.js:2:19508
Menu.prototype.update@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:21612:24
.every@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16468:9
Mode.prototype.every@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16337:18
KeyHandler.prototype.processMode@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16967:12
KeyHandler.prototype.processOnce@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16893:16
KeyHandler.prototype.processKeys@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16886:22
KeyHandler.prototype.handleKey@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16877:19
EventEmitter.prototype.emit/<@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16186:24
EventEmitter.prototype.emit@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16180:1
KeyEmitter.prototype.listen/</<@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:16702:21
n.event.dispatch@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:3:6352
n.event.add/r.handle@http://bitballoon.scdn4.secure.raxcdn.com/bundles/6a49424f12571ef5eb3bc6823b79384ac58a5bdb.js:3:3162

**Comment by paulfchristiano** [comment]
(Exporting my document fixed the problem by removing all marks. I don't know if that was because of this error, or because marks aren't being correctly exported.)

**Comment by WuTheFWasThat** [comment]
i believe this has been fixed, closing for now
