### ISSUE TITLE
Text appears on top of the screen

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#148]
After I type for a long time text appears at the top of the screen, as shown below.

On commit ca7b8892ae23edadf9fe5425db5ad39301f78da5

The problem also appears if I move around between bullets in between typing, I put it all on one screen so you could see how much text was required before the problem appears.

The problem is consistent for me.

Refreshing the page removes the text.

Could give more random observations but it should be pretty easy to replicate.

![screen shot 2016-03-03 at 12 22 21 pm](https://cloud.githubusercontent.com/assets/810371/13508156/b15b97bc-e13a-11e5-965d-52931e148a68.png)

**Comment by paulfchristiano** [comment]
Just verified that it doesn't happen in commit 40d5510bcd2889416c8ae88125137f33d929b334

**Comment by WuTheFWasThat** [comment]
you now have to type 1000x more to get it to happen: https://github.com/WuTheFWasThat/vimflowy/commit/f9970f26230eb73cc3cf83d4c8c5914a50a70da6

**Comment by paulfchristiano** [comment]
That is some ghetto css...
