### ISSUE TITLE
Find a better solution for library sharing

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#152]
https://github.com/WuTheFWasThat/vimflowy/issues/150#issuecomment-198962583
> However, it's somewhat unsatisfactory, since it could break again if lodash changes the way their project is structured. My problem is basically this: I want the node unit tests and browser to be using the same versions of libraries, and node uses npm install. thus, I use a hardcoded location to define the location the client should get lodash from. (if you know of any module loading library that solves this problem, let me know)

**Comment by WuTheFWasThat** [comment]
I should probably just not have "latest" on everything on package.json... that would more or less solve the problem

**Comment by WuTheFWasThat** [comment]
a08781b45ff6fd7a4bd49527abe25e4f0bb62ea4 solved this and i somehow failed to realize this

deleted the unnecessary hardcoding in 9a4e9cf643f757d82e20f561e7db457630de1f6b
