### ISSUE TITLE
QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#154]
When using the Chrome extension, after importing my fairly large WorkFlowy tree, I get this error:
```
Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at chrome-extension://kjpjlojoecfhddakdfcddpafmehihmlp/js/index.js:223:36
```  

See https://developer.chrome.com/apps/storage#properties for information about storage quotas.

**Comment by WuTheFWasThat** [comment]
Hi @alxgnon.

Chrome apps are being deprecated (see https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html).  So I won't be maintaining the chrome app anymore, and I'll never get around to this issue.  Sorry about that!  Let me know if you need to migrate data and have any issues doing that
