### ISSUE TITLE
Should be able to zoom into empty bullet

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#155]
Often, when I'm using Workflowy, I like to create a bullet and then press alt+right to zoom in and start writing about it. This lets you write child bullets while focused and will keep the parent bullet collapsed.

I tried to find an alternative in Vimflowy, but the best I can do right now is create a child element, collapse it, and then zoom in. It should be possible to just press enter on a bullet to focus and start writing about it.

**Comment by WuTheFWasThat** [comment]
yes, that is nice.  I've gotten used to it and not realized.  Currently enter and } have the same behavior, so enter could simply be changed to match that behavior.  should it also put you in insert mode though?

**Comment by alxgnon** [comment]
No, I don't think it should put you in insert mode, because then the `Enter` command would be inconsistent (sometimes you would end up in insert mode, other times no)

I think `Enter` on a empty bullet should just zoom in on the bullet. Pressing `o` or `i` should create the first element and put you in insert mode inside it.

This might not be trivial to implement because it requires being able to zoom into a bullet that doesn't have any children.

**Comment by WuTheFWasThat** [comment]
it would be more natural if it were possible to edit the bullet you're zoomed into, perhaps

**Comment by WuTheFWasThat** [comment]
done: 183ac9ef5c7841f303337720e05b3db473216698
