### ISSUE TITLE
Blank bullet alignment issue

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#156]
![screenshot from 2016-03-20 20 37 27](https://cloud.githubusercontent.com/assets/4480082/13908574/ab134720-eedb-11e5-9a9d-cdfb6880be37.png)
![screenshot from 2016-03-20 20 37 52](https://cloud.githubusercontent.com/assets/4480082/13908575/ac4b3aee-eedb-11e5-8dac-deddeec0cd4b.png)

**Comment by WuTheFWasThat** [comment]
yep, i knew of this.  i had a fix at one point but then it caused highlight+copy/paste to have an extra space :/.  need more css skills

**Comment by alxgnon** [comment]
I believe I can solve this. Will look into it when I have the time

**Comment by WuTheFWasThat** [comment]
that'd be awesome!
