### ISSUE TITLE
Cycle through instances of cloned nodes

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#159]
When I have a node cloned in several places, I often want to jump from one of those places to another.

For example, I have rows that represent tasks in a project. I clone those rows into lists like "Stuff to do on Tuesday." Sometimes I'm happy to view those tasks in the context of "Stuff to do on Tuesday," but sometimes I want to see the surrounding context in the original project. 

It would be great if I could move my cursor to the cloned row and press some key to jump to the next instantiation of that row, maybe zoomed into the parent.

Often this is just a convenience, but in some cases it's actually kind of hard to tell where something came from.

More generally, when I want to link two parts of my document together, I would find this a really nice interface (compared to marks+links).

**Comment by WuTheFWasThat** [comment]
this should be pretty easy, i'll look into it sometime soonish

**Comment by WuTheFWasThat** [comment]
@paulfchristiano `gc` does this now

**Comment by WuTheFWasThat** [comment]
eaf8da43243ea681cb552ad9474997ff391e3cf6
