### ISSUE TITLE
Visual line mode

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#16]

**Comment by WuTheFWasThat** [comment]
done here:  https://github.com/WuTheFWasThat/vimflowy/commit/f9b406ff0c7dbf76469e49610a173d62b05e3b79

still need to do indenting

**Comment by WuTheFWasThat** [comment]
done https://github.com/WuTheFWasThat/vimflowy/commit/ce64c08369df08c33cc8540469457e67c43e6089
