### ISSUE TITLE
Dedent all command?

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#184]
I have the tree:

X
-A [cloned]
--B
Y
-A [cloned]
--B

I would often like to do some kind of "dedent all" on one of the B's. This would transform the tree into

X
-A [cloned]
-B [cloned]
Y
-A [cloned]
-B [cloned]

For example, by typing "y<". I have no idea how easy this is to implement; it's probably not worth it unless it is relatively straightforward. Right now I implement it by cloning B a few times, then dedenting the original.

**Comment by WuTheFWasThat** [comment]
that seems like a pretty strange operation.  since there's a cycle through clones hotkey, it should be possible with a macro that uses that, though, right?

**Comment by paulfchristiano** [comment]
Yeah, not sure how common it is for other people's use cases. It's a tricky for a macro, but the whole thing isn't really that time consuming.
