### ISSUE TITLE
[feature request] have backups say the name of the doc

### ISSUE THREAD

**Issue by tsvibt** [WuTheFWasThat/vimflowy#189]
That is, have the name of the file of a backup say the name of the doc that was backed up.

**Comment by WuTheFWasThat** [comment]
this seems to have been done in https://github.com/WuTheFWasThat/vimflowy/commit/d37cbdc1884e07e0bcbe92cff18fba0fdda2d58d.  are you sure you're updated?

**Comment by tsvibt** [comment]
I see that code in my version (now in session.js), but in fact when I make a backup it doesn't have the document name.

**Comment by WuTheFWasThat** [comment]
so you go to localhost:8080/asdf, hit ctrl+s, and it saves as vimflowy.json?

**Comment by tsvibt** [comment]
yes.

**Comment by WuTheFWasThat** [comment]
my bad, fixed in c70a3538725cd9b35f5fa6bb0e1349dbacd5ce88
