### ISSUE TITLE
Not seeing bullet images in chrome app

### ISSUE THREAD

**Issue by gsastry** [WuTheFWasThat/vimflowy#193]
I don't see any bullet images in the chrome app (but works online): https://www.dropbox.com/s/ubtiqsdydds4i6v/Screenshot%202016-07-21%2015.09.19.png?dl=0

Not sure what's going on?

**Comment by WuTheFWasThat** [comment]
@gsastry thanks for reporting.  it should be fixed now, let me know if not!
