### ISSUE TITLE
desktop app

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#194]
chrome apps are going to be deprecated on all but chrome OS: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Probably should use electron (http://electron.atom.io/)
##

**Comment by caseros** [comment]
For the interim, https://github.com/jiahaog/nativefier works well. (Requires connection to launch, though).

**Comment by joboyx** [comment]
Here's what I do.

In chrome, you can drag the Vimflowy url to chrome://apps page. Right click on the icon and tick Open as New Window. 

Then run Vimflowy as Chrome App. It will now open as a new window/chrome instance and show on your task bar. You can also pin that to your task bar. Works for windows and mac.
