### ISSUE TITLE
"Fullscreen Experience" on Android

### ISSUE THREAD

**Issue by bufke** [WuTheFWasThat/vimflowy#218]
If you add `<meta name="mobile-web-app-capable" content="yes">` and/or set up a Web App Manifest you can make vimflowy feel more like a native app in Android. This lets you launch it without web browser chrome and control what icon it gets on the home screen. It wouldn't be as good as a native app - but it would be pretty simple to implement.

https://developers.google.com/web/fundamentals/native-hardware/fullscreen/#launching_a_page_fullscreen_from_home_screen

**Comment by WuTheFWasThat** [comment]
Cool, thanks!  I didn't know about that.  I just did the easy meta tags addition for now: 2b15ae2d4e53c9b2e0747e5bb7d43746397747d0

I'm curious - is vimflowy actually usable in mobile for you, though?

**Comment by bufke** [comment]
Mostly. I'm using it with a Pixel C and keyboard. Using firebase sync with my desktop. Reloading to sync is "good enough" if not ideal. 

Biggest problem is that for some reason the shortcut for escape (no escape key on the pixel C) is the same for go back in chrome (so stupid). I wonder if this would get bypassed in the fullscreen mode. Not really a vimflowy issue.

**Comment by WuTheFWasThat** [comment]
you could remap the key for escape if you're able to download/modify/reupload a json file.  I should just make a non-modal mode though that behaves more like workflowy

**Comment by bufke** [comment]
Just some follow up - vimflowy is working great on my Pixel C and syncing with desktop! It's my primary note taking software at work now. Thanks!
