### ISSUE TITLE
Hotkey settings aren't saved

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#221]
When I import hotkeys from a file it works fine. When I refresh the page, the hotkeys are restored to the defaults.

(On commit 07c291c6544b256cd29, using firebase for storage.)

**Comment by WuTheFWasThat** [comment]
d4187cfe2707fd8d30ff4fa170a9d4e33877e648

**Comment by WuTheFWasThat** [comment]
err, actually 7d9f560
