### ISSUE TITLE
Using plugins?

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#222]
After updating, I no longer see a way to use either easy motion or the time tracking plugin. (Time tracking is working, I just can't use or set any of the associated hotkeys.)

On commit 07c291c6544b256cd29

**Comment by WuTheFWasThat** [comment]
That's odd.  In the settings menu, plugin tab, does it show time-tracking/easy-motion as on?

**Comment by paulfchristiano** [comment]
I no longer have the problem in commit bb0da0faa4. (They did show up as "enabled" when I was having the problem.)

**Comment by paulfchristiano** [comment]
Problem was importing hotkey file that didn't have any hotkey set for easy motion.

**Comment by WuTheFWasThat** [comment]
sorry, user friendliness is not the best lol
