### ISSUE TITLE
Div Display Error

### ISSUE THREAD

**Issue by caseros** [WuTheFWasThat/vimflowy#243]
![image](https://cloud.githubusercontent.com/assets/23514556/24701490/fd78a314-1a3d-11e7-91b0-a4b1e07a6491.png)

At the bottom, I believe it's `#message`. Will investigate later.

 
---

- OS X 10.10.3
- Chrome 57.0.2987.133

**Comment by WuTheFWasThat** [comment]
I'm not seeing this behavior on the same version of chrome (OS X 10.12 but i dont think that should matter)

**Comment by WuTheFWasThat** [comment]
@caseros this still happening for you?

**Comment by caseros** [comment]
Oops, sorry! ("investigate later" -- total lie!)

Yeah, still happening. Both Firefox and Chrome (sans extensions and incognito, too). 

Just tried via Guest login and there's no error...

**Comment by WuTheFWasThat** [comment]
Haha no problem.  I still dunno how to repro, though :(

**Comment by WuTheFWasThat** [comment]
@sagarjauhari @caseros do you know if it happens immediately on page load? or is it only after vimflowy tries to display a message?

**Comment by sagarjauhari** [comment]
When I reloaded the app I did not see the issue. I think it happens on page load and if I notice the issue again I'll comment here.

**Comment by WuTheFWasThat** [comment]
I'm just guessing here, but I made some changes to code I suspected caused the issue, so maybe it's fixed now.. let me know if it still happens
