### ISSUE TITLE
Display error when a yanked clone cannot be pasted

### ISSUE THREAD

**Issue by sagarjauhari** [WuTheFWasThat/vimflowy#245]
Currently, if a yanked clone is pasted as a sibling or descendent - the pasting doesn't happen but no error or notification is shown. Would be good to have an error message somewhere.

**Comment by WuTheFWasThat** [comment]
there's supposed to be a message on the status line at the bottom.  is it not showing for you, or did you miss it?  it's pretty easy to miss but I wanted to stick to vim's non-intrusive style.  (suggestions appreciated)

**Comment by sagarjauhari** [comment]
oh, in that case there's some issue with the message display: [giphy](http://www.giphy.com/gifs/3o7bucyaPyNOmL8XFS)

This is Chrome Version 58.0.3029.96 (64-bit), Mac

**Comment by WuTheFWasThat** [comment]
ah this is a case of #243.  will look into it!
