### ISSUE TITLE
Test for supported browser by feature detection instead of user agent detection

### ISSUE THREAD

**Issue by berrunder** [WuTheFWasThat/vimflowy#247]
In Opera browser alert show up after page load because of [this line](https://github.com/WuTheFWasThat/vimflowy/blob/6b3df4adc035c059cd6ca552e4826ef124d6b1df/src/assets/ts/keyEmitter.ts#L23). After that app works perfectly fine, all features supported - because modern Opera browser uses the same Blink engine as Chrome.
It's very small annoyance for me, but can confuse some future users. I think this alert should be either removed or shown only if browser really doesn't support essential features (maybe use Modernizr for feature detecion?).

**Comment by WuTheFWasThat** [comment]
Thanks for raising this.  It is much too strict, as is.  I'll work on fixing it

**Comment by WuTheFWasThat** [comment]
f62cb9a0de6854ce3495de7f56bb45502868ab0c
