### ISSUE TITLE
Keyboard layouts other than QWERTY don't work properly

### ISSUE THREAD

**Issue by Janiczek** [WuTheFWasThat/vimflowy#248]
I use Czech QWERTZ sometimes:

![Czech QWERTZ layout](http://www.ceskaklavesnice.cz/images/klvs_cs_norm.jpg)

Vimflowy doesn't respect that:
- the key `ě` (without Shift) gets written as `2`,
- similarly `2` (the same key pressed with Shift) gets written as `@`.

**Comment by Janiczek** [comment]
Oh, and just found out: even when I'm on the English QWERTY layout, pressing `AltGr` writes `á`.

**Comment by WuTheFWasThat** [comment]
Not quite a duplicate of #147, but will hopefully be solved in the same way
