### ISSUE TITLE
Feature request: Tags

### ISSUE THREAD

**Issue by mortyccp** [WuTheFWasThat/vimflowy#249]
Current, mark can only be unique. I would like to know why the marks plugin have this limitation. Can it allow the same mark used on multiple lines?

**Comment by WuTheFWasThat** [comment]
The problem is that you can have [@markname] link to the location - it's intended for that use cases.  I think your use case is also valid though.  Workflowy calls them "tags", and they can perhaps be implemented similarly to marks.

**Comment by platers** [comment]
btw I think this can be closed #364
