### ISSUE TITLE
[internal] rethink data/view separation

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#25]

**Comment by CurtisSV** [comment]
I already thought this through a bit for my open-source workflowy. 

-You need to make sure that each model/json-representing-a-node/vertex/bullet can have multiple views associated with it. That way, you can do something like `models.views.each |v| v.updateText()` to update all the views of a bullet. You can also have views nested within other views (i.e. A node has itself as an ancestor). It's tricky to implement recursive rendering without good separation of data and views. 
-Each view captures expand/collapse and typing clicks/events. 
-Each node should have parents[] as well as a child[].

**Comment by WuTheFWasThat** [comment]
hey curtis!

all of that should be totally possible (and fairly easy).  only annoyance is migrating from `parent` to `parents[]`.   Thanks for the comments

**Comment by za3k** [comment]
All right, going to call this solved between aliasing and virtual DOM
