### ISSUE TITLE
Data is transient

### ISSUE THREAD

**Issue by Immortalin** [WuTheFWasThat/vimflowy#254]
Data is not retained after application is closed.

**Comment by WuTheFWasThat** [comment]
Are you using incognito/private browsing?  Or perhaps using a browser that doesn't support localStorage (unlikely)?  If not, could you give me more details (browser, vimflowy setup if not bitballoon, etc.)?

**Comment by Immortalin** [comment]
@WuTheFWasThat nope, just standard browsing. Browser is `Chrome Version 59.0.3071.86 (Official Build) (64-bit)`. Problem occurs on both Ubuntu 16.04 and Windows 10, default vimflowy settings.

**Comment by WuTheFWasThat** [comment]
Just tried with the same chrome version on OS X, and it seems fine.  Maybe it's because of some extension?  Anything suspicious in the javascript console perhaps?

**Comment by Immortalin** [comment]
How should I activate the js console in vimflowy?

**Comment by WuTheFWasThat** [comment]
something like "View > Developer > Javascript console"

**Comment by Immortalin** [comment]
@WuTheFWasThat I can't access the toolbar in vimflowy

**Comment by WuTheFWasThat** [comment]
oh, are you using the version from the chrome web store?  that's not supported now.  you can use the one at vimflowy.bitballoon.com instead, if so
