### ISSUE TITLE
Plugin to make default search only look at subtree?

### ISSUE THREAD

**Issue by MilesCranmer** [WuTheFWasThat/vimflowy#256]
Hi, this is a great app! I was wondering if there is a plugin/setting I can use so that search ("/") only searches on the current subtree? Right now it seems to search the entirety of everything I have ever written, which is not what vim nor workflowy has by default (they search from the current line/subtree), so it feels a little unnatural.

Thanks!

Miles

**Comment by fullyint** [comment]
I wonder if [`search-local`](https://github.com/WuTheFWasThat/vimflowy/blob/1f69932c7af635c478ce190e3e7905f92b388baf/src/assets/ts/configurations/vim.ts#L111-L112) would do it: `ctrl + /` or `ctrl + f`

**Comment by MilesCranmer** [comment]
Thanks, @fullyint, that got it! Closing.

**Comment by WuTheFWasThat** [comment]
yep, it does!  I went back and forth on which one should be the default... any other opinions?

**Comment by MilesCranmer** [comment]
I prefer `/` being default local search, as I can always do a `shift+enter` then `/` if I want to global search, but that's just me
