### ISSUE TITLE
Navigation slow when running locally

### ISSUE THREAD

**Issue by bpierce1** [WuTheFWasThat/vimflowy#259]
This is a great tool! I followed the instructions to setup the dev environment, and I got it running, but it seems that navigation is noticeably slower than using https://vimflowy.bitballoon.com/# even for a very small document. 

Any suggestions?

One of the main reasons I'd like to have it running locally is that it'd be great to be able to use this when fully offline. Right now, if I lose the vimflowy tab, I can't reconnect unless I'm online.

**Comment by WuTheFWasThat** [comment]
Hi!  This is likely because the assets are compiled in an unoptimized way.

Instead of doing `npm start`, you should do `npm start -- --build --prod`.  I'll add some documentation!

**Comment by bpierce1** [comment]
Yep, fixed it! Thanks!
