### ISSUE TITLE
Terminal / vim version?

### ISSUE THREAD

**Issue by bpierce1** [WuTheFWasThat/vimflowy#260]
This is a really great tool. I'm curious if you have any plans to put together some sort of similar version as a plugin for vim? I've looked around, and there are a couple things that are roughly similar, but none of them work nearly as well as your version. Of course there's some browser functionality that would be hard to replicate, but even a stripped down version would be very useful.

**Comment by WuTheFWasThat** [comment]
I have no plans, and as far as I can tell, that would involve an entirely separate codebase.  This project runs on javascript, and I can't imagine there's a way to port the functionality to vim besides a rewrite :(

Have you tried spacemacs with the org-layer?  It might be closer to what you want than some of the vim plugins you tried

**Comment by bpierce1** [comment]
I did! Unfortunately, I just don't like spacemacs. I found it harder to configure precisely how I wanted it, and in general too heavy weight. Maybe I just didn't spend enough time getting it set up properly. 

Oh well - browser version is really nice!
