### ISSUE TITLE
Something wrong with scrolling on master when running locally

### ISSUE THREAD

**Issue by bpierce1** [WuTheFWasThat/vimflowy#261]
It looks like somethings going wrong when I run locally and have more items visible than fit on a page. Moving the cursors to the bottom of the screen doesn't cause the bullets to move.

This issue doesn't seem to exist on https://vimflowy.bitballoon.com/# though.

Any suggestions? Is there a better commit to use than bb146ade26d0a2a4bf868f600b248847ac1a127b

![Uploading Screen Shot 2017-07-20 at 8.18.35 AM.png…]()

**Comment by WuTheFWasThat** [comment]
thanks for reporting - d583ffc should be working.  looking to fix it on master now

**Comment by WuTheFWasThat** [comment]
fixed in f9b85ae36a595bc46641bb01013097c7be154bbb

**Comment by bpierce1** [comment]
looks good, thanks!
