### ISSUE TITLE
Enable the server to run from vanilla node

### ISSUE THREAD

**Issue by willprice** [WuTheFWasThat/vimflowy#265]
**The problem?** 

Currently the dependencies of the server are very entangled with the webpack building deps making it impossible to deploy the server in a lightweight environment without all the typescript and webpack dependencies.

**A solution:**

Ideally the server should be separated into two independent modules, one the development server dependent upon webpack and the other light weight with only the dependencies necessary for the WS server (+ static file serving).

**Comment by WuTheFWasThat** [comment]
yeah, that's a good point.  here's a tentative plan:
- separate index.ts into two separate files
- make devDependencies in package.json correspond to what's needed to build and run the dev server

what do you think?  i dunno if it's the most principled/best thing still.  and the modules wouldn't really be independent - you'll need all the regular dependencies for dev (after all, the dev server can also run sqlite etc).

**Comment by willprice** [comment]
I think your suggestion seems reasonable. I had a quick go at doing this but it started snowballing fairly quickly. Here's the approach I'd take:

* Move the production server deps into `dependencies` from `devDependencies`
* Isolate the config common to both dev and prod server
* Split out index to dynamically dispatch to either dev server or prod server based on `NODE_ENV` env var (in addition to having a `--prod` flag).
* Add new targets in `package.json` to build a shippable version of vimflowy production server + client side assets

**Comment by WuTheFWasThat** [comment]
by dynamically dispatch you mean `if (blah) require('./dev')` type of thing?  would the main value of index be so it's easier to toggle between dev and prod?  that was what I was thinking back when I wrote it, but I'm now getting skeptical it's helpful

**Comment by willprice** [comment]
Yep exactly. To keep things a little cleaner I'd probably split out the dev server and prod server into two separate file which are required inside the condition in the main index file. Thoughts? I'm not wedded to the idea but I think it'd be quite valuable to be able to split out the deps (not just for the docker work, but for anyone hosting with the sqlite backend).

**Comment by willprice** [comment]
For a bit more context, here's the reason that made me desire this separation:

```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
90b3ecccc5b8        10 hours ago        /bin/sh -c #(nop)  ENTRYPOINT ["/bin/sh" "...   0B
16af0edbe8d4        10 hours ago        /bin/sh -c #(nop)  ENV VIMFLOWY_PASSWORD=v...   0B
67141d679f97        10 hours ago        /bin/sh -c #(nop)  EXPOSE 3000/tcp              0B
193999f96b2f        10 hours ago        /bin/sh -c #(nop)  VOLUME [/app/db]             0B
842efd043f61        10 hours ago        /bin/sh -c #(nop) WORKDIR /app                  0B
116e08f2bb4d        10 hours ago        /bin/sh -c npm run build                        4MB
560fdb832147        10 hours ago        /bin/sh -c #(nop) COPY dir:8fe7db075d331f1...   4.91MB
23dd2ccd2957        12 hours ago        /bin/sh -c npm install                          168MB
7ba91ed5b0cc        12 hours ago        /bin/sh -c #(nop) COPY multi:ee9437cdc048b...   241kB
d14cf69e6a03        12 hours ago        /bin/sh -c #(nop) WORKDIR /app/                 0B
115d8fa80c6d        12 hours ago        /bin/sh -c apt-get update -qq &&     apt-g...   15.7MB
d0cccfe32901        12 hours ago        /bin/sh -c #(nop)  LABEL version=0.0.1          0B
38f6c68d9466        12 hours ago        /bin/sh -c #(nop)  LABEL maintainer=will.p...   0B
6d71556f616a        3 days ago          /bin/sh -c #(nop)  CMD ["node"]                 0B
<missing>           3 days ago          /bin/sh -c set -ex   && for key in     6A0...   3.89MB
<missing>           3 days ago          /bin/sh -c #(nop)  ENV YARN_VERSION=0.27.5      0B
<missing>           3 days ago          /bin/sh -c ARCH= && dpkgArch="$(dpkg --pri...   42.9MB
<missing>           3 days ago          /bin/sh -c #(nop)  ENV NODE_VERSION=6.11.3      0B
<missing>           3 days ago          /bin/sh -c #(nop)  ENV NPM_CONFIG_LOGLEVEL...   0B
<missing>           3 days ago          /bin/sh -c set -ex   && for key in     955...   130kB
<missing>           3 days ago          /bin/sh -c groupadd --gid 1000 node   && u...   333kB
<missing>           3 days ago          /bin/sh -c set -ex;  apt-get update;  apt-...   555MB
<missing>           3 days ago          /bin/sh -c apt-get update && apt-get insta...   142MB
<missing>           3 days ago          /bin/sh -c set -ex;  if ! command -v gpg >...   8.11MB
<missing>           3 days ago          /bin/sh -c apt-get update && apt-get insta...   23.8MB
<missing>           4 days ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           4 days ago          /bin/sh -c #(nop) ADD file:a7405474b639b22...   100MB
```

This line:

```
23dd2ccd2957        12 hours ago        /bin/sh -c npm install                          168MB
```

168MB of deps in the docker image (on rural broadband this is death by a thousand needles!)

**Comment by WuTheFWasThat** [comment]
it's possible to now do `mkdir blah; npm run buildserver -- --outdir blah`, and then `node blah/server.js --staticDir static`.  this node server will have very minimal dependencies (express, ws, lodash, maybe a few others)
