### ISSUE TITLE
autoconfig for socket server

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#267]
See https://github.com/WuTheFWasThat/vimflowy/pull/264#issuecomment-330000729

in socket server case, should essentially auto configure socketServerHost in the client.  can be accomplished with DefinePlugin

**Comment by willprice** [comment]
> RE client autoconfig: I don't think it makes sense to have the server pre-configure the password. So in the server case there needs to be some other UI for passwords... I have a WIP on the branch socketserver_autoconfig though. I'm going to open an issue for that.

Yeah, here's my envisaged user flow:

* Visits http://my-vimflowy-server.com
* Is prompted whether she wants to use local storage or server backend (sqlite)
* She selects server 
* She is prompted for server pw
* She inputs server pw
* She is prompted for db name
* Enter db name
* Starts using vimflowy now the backend is configured

**Comment by WuTheFWasThat** [comment]
I had been thinking the only configuration would be password

- it would automatically use sqlite over local storage
- db name would be same as docname, i.e. ?doc={dbname}

in the case of no password, there would be no configuration.  what do you think?  I guess the main question is whether people would run the sqlite server and still want local storage.  Those could use a separately hosted static version I think

**Comment by willprice** [comment]
I like your suggestion better, it's a more frictionless user workflow. :+1: 

We prompt user to enter the password if the server has one?

**Comment by WuTheFWasThat** [comment]
yep that's right

**Comment by WuTheFWasThat** [comment]
but i think you meant user vimflow*

**Comment by WuTheFWasThat** [comment]
c70531e6884206c45563a39470da5315bb1b4c3f
