### ISSUE TITLE
text format expands in normal mode

### ISSUE THREAD

**Issue by delta4d** [WuTheFWasThat/vimflowy#280]
Is text format expanding in normal mode intended?

IMHO, insert mode expands formatting is ok. Normal is some way like _view_ mode, but when the cursor is on the line contains text format, it expands to something like `......  **text formating** ...`, which is distracts me.

Is this the intended behavior?

**Comment by WuTheFWasThat** [comment]
Yeah, it's intended.  I agree it's unfortunate sometimes when you want to view.  But I think of normal mode as an editing mode, just like insert mode.  Also, normal vim movement should all make sense in normal mode, for example. Displaying rich text makes that very confusing
