### ISSUE TITLE
Scrolling doesn't follow cursor

### ISSUE THREAD

**Issue by dlip** [WuTheFWasThat/vimflowy#284]
When moving the cursor down it goes off the screen but you have to use the mouse to scroll. It should move with the cursor.

**Comment by WuTheFWasThat** [comment]
thanks!  i'm investigating... it seems to only happen on netlify, not locally, which makes it trickier to debug.  is that where you're using vimflowy?

**Comment by WuTheFWasThat** [comment]
Fixed in 0a405b761cdfbd04a6672ebc4561a5b50c4a35fc
