### ISSUE TITLE
Fail on 'npm run build`

### ISSUE THREAD

**Issue by BrianD91** [WuTheFWasThat/vimflowy#288]
I am trying to setup Vimflowy locally. Following the guide here https://github.com/WuTheFWasThat/vimflowy/blob/master/docs/storage/SQLite.md

My plan is to have the local SQLite db and then use syncthing to share it across multiple devices. However when I run the 'npm run build' command I get this message:

 

> vimflowy@0.0.1 build /home/hal-9000/vimflowy-setup/vimflowy
>  ts-node src/server/build.ts
> 
> sh: 1: ts-node: not found
> 
> npm ERR! Linux 4.15.0-29-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! vimflowy@0.0.1 build: `ts-node src/server/build.ts`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the vimflowy@0.0.1 build script 'ts-node src/server/build.ts'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the vimflowy package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node src/server/build.ts
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vimflowy
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls vimflowy
> npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/hal-9000/vimflowy-setup/vimflowy/npm-debug.log

Here's the output of the npm-debug.log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
> 2 info using npm@3.5.2
> 3 info using node@v8.10.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle vimflowy@0.0.1~prebuild: vimflowy@0.0.1
> 6 silly lifecycle vimflowy@0.0.1~prebuild: no script for prebuild, continuing
> 7 info lifecycle vimflowy@0.0.1~build: vimflowy@0.0.1
> 8 verbose lifecycle vimflowy@0.0.1~build: unsafe-perm in lifecycle true
> 9 verbose lifecycle vimflowy@0.0.1~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/hal-9000/vimflowy-setup/vimflowy/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 10 verbose lifecycle vimflowy@0.0.1~build: CWD: /home/hal-9000/vimflowy-setup/vimflowy
> 11 silly lifecycle vimflowy@0.0.1~build: Args: [ '-c', 'ts-node src/server/build.ts' ]
> 12 info lifecycle vimflowy@0.0.1~build: Failed to exec build script
> 13 verbose stack Error: vimflowy@0.0.1 build: `ts-node src/server/build.ts`
> 13 verbose stack spawn ENOENT
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid vimflowy@0.0.1
> 15 verbose cwd /home/hal-9000/vimflowy-setup/vimflowy
> 16 error Linux 4.15.0-29-generic
> 17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> 18 error node v8.10.0
> 19 error npm  v3.5.2
> 20 error file sh
> 21 error code ELIFECYCLE
> 22 error errno ENOENT
> 23 error syscall spawn
> 24 error vimflowy@0.0.1 build: `ts-node src/server/build.ts`
> 24 error spawn ENOENT
> 25 error Failed at the vimflowy@0.0.1 build script 'ts-node src/server/build.ts'.
> 25 error Make sure you have the latest version of node.js and npm installed.
> 25 error If you do, this is most likely a problem with the vimflowy package,
> 25 error not with npm itself.
> 25 error Tell the author that this fails on your system:
> 25 error     ts-node src/server/build.ts
> 25 error You can get information on how to open an issue for this project with:
> 25 error     npm bugs vimflowy
> 25 error Or if that isn't available, you can get their info via:
> 25 error     npm owner ls vimflowy
> 25 error There is likely additional logging output above.
> 26 verbose exit [ 1, true ]

**Comment by WuTheFWasThat** [comment]
you ran `npm install`, right?  if so, I believe there should be something at ./node_modules/.bin/ts-node.  Is that there for you?

**Comment by WuTheFWasThat** [comment]
sounds like you got past this issue
