### ISSUE TITLE
Fail on npm install

### ISSUE THREAD

**Issue by BrianD91** [WuTheFWasThat/vimflowy#292]
Hey! It's me again, I've got vimflowy running on my laptop just fine. But now am having trouble getting it setup on my desktop. Both systems are running Kubuntu 18.04 LTS.

Here's the output when I run `sudo npm install`

> > grpc@1.11.3 install /home/hal-9000/vimflowy/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> [grpc] Success: "/home/hal-9000/vimflowy/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" is installed via remote
> 
> > node-sass@4.9.2 install /home/hal-9000/vimflowy/node_modules/node-sass
> > node scripts/install.js
> 
> Unable to save binary /home/hal-9000/vimflowy/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/hal-9000/vimflowy/node_modules/node-sass/vendor'
>     at Object.mkdirSync (fs.js:738:3)
>     at sync (/home/hal-9000/vimflowy/node_modules/mkdirp/index.js:71:13)
>     at Function.sync (/home/hal-9000/vimflowy/node_modules/mkdirp/index.js:77:24)
>     at checkAndDownloadBinary (/home/hal-9000/vimflowy/node_modules/node-sass/scripts/install.js:114:11)
>     at Object.<anonymous> (/home/hal-9000/vimflowy/node_modules/node-sass/scripts/install.js:157:1)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>   errno: -13,
>   syscall: 'mkdir',
>   code: 'EACCES',
>   path: '/home/hal-9000/vimflowy/node_modules/node-sass/vendor' }
> 
> > sqlite3@4.0.2 install /home/hal-9000/vimflowy/node_modules/sqlite3
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> [sqlite3] Success: "/home/hal-9000/vimflowy/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" is installed via remote
> 
> > node-sass@4.9.2 postinstall /home/hal-9000/vimflowy/node_modules/node-sass
> > node scripts/build.js
> 
> Building: /usr/local/bin/node /home/hal-9000/vimflowy/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ '/usr/local/bin/node',
> gyp verb cli   '/home/hal-9000/vimflowy/node_modules/node-gyp/bin/node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.7.0
> gyp info using node@10.6.0 | linux | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` succeeded python2 /usr/bin/python2
> gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.15rc1\n"
> gyp verb get node dir no --target version specified, falling back to host node version: 10.6.0
> gyp verb command install [ '10.6.0' ]
> gyp verb install input version string "10.6.0"
> gyp verb install installing version: 10.6.0
> gyp verb install --ensure was passed, so won't reinstall if already installed
> gyp verb install version is already installed, need to check "installVersion"
> gyp verb got "installVersion" 9
> gyp verb needs "installVersion" 9
> gyp verb install version is good
> gyp verb get node dir target node version installed: 10.6.0
> gyp verb build dir attempting to create "build" dir: /home/hal-9000/vimflowy/node_modules/node-sass/build
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/hal-9000/vimflowy/node_modules/node-sass/build'
> gyp ERR! System Linux 4.15.0-29-generic
> gyp ERR! command "/usr/local/bin/node" "/home/hal-9000/vimflowy/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /home/hal-9000/vimflowy/node_modules/node-sass
> gyp ERR! node -v v10.6.0
> gyp ERR! node-gyp -v v3.7.0
> gyp ERR! not ok 
> Build failed with error code: 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/webpack-dev-server/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.9.2 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/hal-9000/.npm/_logs/2018-08-02T21_58_23_078Z-debug.log

**Comment by WuTheFWasThat** [comment]
See https://github.com/sass/node-sass/issues/1098 and https://github.com/angular/angular-cli/issues/6848.  

If those threads don't help, then it's possible this is a result of b3795be18e28ed7a51c13398517ddd64a2531981.  Could you try going back to before that commit and reinstalling packages?  

Let me know how it goes!
