### ISSUE TITLE
Possible to run as static html without server?

### ISSUE THREAD

**Issue by mobitar** [WuTheFWasThat/vimflowy#295]
Hello, is it possible to serve this as a static html page without a server? It seems like it would be, but I'm running into the following issue:

After running `npm run build`, I do see the build folder generated with app.js. However, when I load the index.html file directly in the browser, I see the following error:

```
app.js:81 Uncaught SyntaxError: Invalid regular expression: /([ 
	]+)|([!-\[\]-â€§â€ª-íŸ¿ï¤€-ï¿¿]|[�-�][�-�]|\\(?:[a-zA-Z]+|[^�-�]))/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (app.js:81)
    at n (app.js:1)
```

This issue does not appear when running it through the dev or prod server.

**Comment by WuTheFWasThat** [comment]
yep, it should be.  thanks for reporting!  I'm able to reproduce on a recent version of chrome, so that's definitely an issue..  I've been a bit busy, but will look into it hopefully tonight

**Comment by mobitar** [comment]
Can confirm this works now, thanks 👍
