### ISSUE TITLE
Error when loading from firebase

### ISSUE THREAD

**Issue by rogershijin** [WuTheFWasThat/vimflowy#297]
I tried to access vimflowy on 11/18/18 3:49 am EST and got this error on Firefox Quantum 60.0.2 on Arch Linux: 
![image](https://user-images.githubusercontent.com/27650355/48670373-ea59d900-eae4-11e8-9b3b-ae99200433ff.png)

**Comment by WuTheFWasThat** [comment]
sorry about that!  fixed now.  you may have to switch back to the firebase backend in settings
