### ISSUE TITLE
Clone/batch clone from Search

### ISSUE THREAD

**Issue by 8utl3r** [WuTheFWasThat/vimflowy#309]
Not sure where to put this feature request. Sorry, if this is the wrong place. :) I'd love to be able to clone and batch clone from the search focus mode. Usage as follows:
1. I've tagged a bunch of bullets with "#puppystuff" in various locations with different parents 
2. Now that I'm actually getting a dog I want to pull all those scattered thoughts to a single place so I search for "#puppystuff" and 16 bullets pop up. 
3. I hit a key and it clones all 16 bullets and pops me back to Normal mode
4. Insert a new bullet called "Living the Dog life" and insert the clones below it.

Instant 'view' containing all relevant bullets. It gives superpowers to clones. 
I suppose it would also be useful to add a standard copy option as well if you don't want to modify the originals. Then you could use the feature for template making. A separate key for single line copy/clone depending on line focus would also be incredible. The search screen seems wildly underutilized. Batch actions from Search, in general, would be incredibly powerful.

If this feature already exists in some fashion... I'm sorry lol. I've tried to find it but can't. :( 

Thanks for your time!

**Comment by WuTheFWasThat** [comment]
Being able to do stuff in search mode does seem useful but I'm unlikely to implement it (but you're welcome to try!) 

- Search is actually generally inefficient, so I'd recommend against workflows using it once you have a large enough document
- the interface might be a bit tricky for actions from search

Semi-related and possibly something in this space would partially solve your problem:  https://github.com/WuTheFWasThat/vimflowy/issues/249

**Comment by 8utl3r** [comment]
well darn... I'll just do it another way. :P Thanks!
