### ISSUE TITLE
Unable to sync with Firebase

### ISSUE THREAD

**Issue by jamesjryan** [WuTheFWasThat/vimflowy#316]
Hi there, I've been using Vimflowy with Firebase for years, however it stopped working a few months ago with the following error when trying to authenticate:

```
Error loading firebase datastore

The password is invalid or the user does not have a password.

undefined

Falling back to localStorage default.
```

The call to `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=somekeyhere` is failing with 

```
{
  "error": {
    "code": 400,
    "message": "INVALID_PASSWORD",
    "errors": [
      {
        "message": "INVALID_PASSWORD",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

I've checked and I'm certainly using the correct password.

**Comment by WuTheFWasThat** [comment]
hmm, I have an instance with firebase as well and haven't had an issue.  

Maybe try double checking the auth rules or adding a new user?  https://github.com/WuTheFWasThat/vimflowy/blob/master/docs/storage/Firebase.md

**Comment by jamesjryan** [comment]
Problem between the chair and the keyboard - simply the wrong firebase password - cheers.
