### ISSUE TITLE
Indent / outdent block

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#33]

**Comment by WuTheFWasThat** [comment]
what is this?  if it means indent/outdent a bullet and all its ancestors, then this already exists

**Comment by vanceza** [comment]
What's the shortcut key?

**Comment by vanceza** [comment]
Also yes, that's exactly what I mean.

**Comment by WuTheFWasThat** [comment]
ctrl+h and ctrl+l
