### ISSUE TITLE
Advice about development daily notes plugin

### ISSUE THREAD

**Issue by shady2k** [WuTheFWasThat/vimflowy#332]
Need advice. It is required to put a tag, for example "today" on the record, when a new day comes. Can I subscribe to events on time from the plugin somehow? This is necessary for the implementation of daily notes for a quick transition to today's recording.

**Comment by WuTheFWasThat** [comment]
someone had started something very similar here!  

https://github.com/WuTheFWasThat/vimflowy/pull/300

**Comment by shady2k** [comment]
Thanks.
