### ISSUE TITLE
Carriage returns are recognized as empty chars on import via plaintext file

### ISSUE THREAD

**Issue by MMDF** [WuTheFWasThat/vimflowy#341]
I have imported over my data from workflowy and after import there was one char at the end of each line that my cursor disappeared on selecting. After some looking around I found that that char was a carriage return \r char. 

Vimflowy should discard carriage returns entirely imo. This was really annoying because my cursor disappeared many times and it took me some time to understand the situation.

**Comment by MMDF** [comment]
Also confirming that the problem of the cursor disappearing is solved by running the exported plaintext file through dos2unix and reimporting.

**Comment by WuTheFWasThat** [comment]
attempted fix here https://github.com/WuTheFWasThat/vimflowy/commit/cae875ff89fb29c8d05e4a5bacaa1729fbd8dd4d, let me know if it still isn't fixed

**Comment by MMDF** [comment]
The issue seems to be fixed, thanks.
