### ISSUE TITLE
Can't navigate after exiting insert mode

### ISSUE THREAD

**Issue by kalons7** [WuTheFWasThat/vimflowy#342]
When initially opening vimflowy, pressing j and k can be used to go down / up, but after pressing i for insert mode, typing some text, then cancelling (and it seems that Esc needs to be pressed twice to do this, why?), j and k stop working.  I have to click with the mouse on a row, and then it starts working again.  But of course, I don't want to reach for the mouse.  Can this be fixed?

**Comment by WuTheFWasThat** [comment]
Are you using vimium or something like that?

**Comment by kalons7** [comment]
Yes, I'm using Vimium.  I did try to add an exclusion for vimflowy before, and it finally worked on the third try.  Thanks.
