### ISSUE TITLE
Don't capture every key

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#35]
In particular, you're capturing important browser keys: `ctrl+r`, `ctrl+shift+j` etc. I think the default should be to let keys pass through if we can't figure out what to do with them.

**Comment by WuTheFWasThat** [comment]
yep - i agree that's better behavior

**Comment by WuTheFWasThat** [comment]
still not implemented properly, though now you can't type arbitrary things in insert mode, at least.  and there's a whitelist of allowed things (as you've noticed :P)

**Comment by vanceza** [comment]
Working on this in unhandled_keys, I also saw a dont_capture_keys, is that active or even related?

**Comment by WuTheFWasThat** [comment]
hmm i'm not sure what either of those refers to - but to expand a bit:  keyEmitter.coffee needs to return true or false based on whether someone (namely keyHandler.coffee) actually hears the event it emits

**Comment by vanceza** [comment]
Yep, I did all of the parts outside keyHandler.coffee already.

**Comment by WuTheFWasThat** [comment]
done properly now!
