### ISSUE TITLE
Docker build failed: no such file or directory

### ISSUE THREAD

**Issue by platers** [WuTheFWasThat/vimflowy#358]
I cloned the repo and tried to deploy it with docker and got this error on step 20. This happens on both heroku and gcloud. Any idea whats happening?

Step 17/24 : COPY --from=build /build/server/* ./
 ---> 30ce7f934378
Step 18/24 : RUN mkdir -p /app/static
 ---> Running in db12baf04c9a
Removing intermediate container db12baf04c9a
 ---> eefc84e59cdf
Step 19/24 : COPY --from=build /app/static/* /app/static/
 ---> f9f8aff3ec7d
Step 20/24 : COPY --from=build /build/client /app/static/build
COPY failed: stat /var/lib/docker/overlay2/034a760f02f71e84eead0507aa2d8c017e1ed35c2ebb5a92ad1aa00a2a9f9549/merged/build/client: no such file or directory
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1

**Comment by WuTheFWasThat** [comment]
ah jeez, sorry, this probably just hasn't been tested in a long time.  could you try changing `/build/client` to `/build` perhaps?  sorry, I'm too busy these days to maintain this project much :(

**Comment by platers** [comment]
Thanks, that seems to work. The build completes now, though I still can't get it to start on heroku. A guide to deploying on heroku would be really nice to have. Thanks for all the work you've done already, vimflowy is awesome!

**Comment by WuTheFWasThat** [comment]
what happens on heroku?  i'm also having issues with the production deploy all of a sudden, despite nothing having really changed :(

**Comment by platers** [comment]
It gives me a H-10 app crashed error when it tries to start the app. I dont know how to get more detailed logs :/

**Comment by WuTheFWasThat** [comment]
I just pushed some changes to master, hopefully the docker build is fixed now

**Comment by platers** [comment]
I havn't tested docker yet but npm install now fails with a ton of 
npm WARN tar ENOENT: no such file or directory, open '....\vimflowy\node_modules\.staging\react-color-878bd3ce\lib\components\photoshop\story.js'

**Comment by WuTheFWasThat** [comment]
hm, from a google search, it's possible you just have to `rm -r node_modules` and redo `npm install`?  it works for me though, I think it's probably not an issue with vimflowy this time

**Comment by platers** [comment]
Yup the issue was on my side. I got the dev server running locally after updating node, deleting package-lock.json, and `npm cache clean --force`

**Comment by WuTheFWasThat** [comment]
hm, that's too bad that package-lock.json had to be deleted :/ but glad it worked!
