### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by kristijanhusak** [WuTheFWasThat/vimflowy#359]
I wanted to check the demo link from readme (https://vimflowy.netlify.app/), but it's not working. Only blank page.

**Comment by WuTheFWasThat** [comment]
ugh, thanks for letting me know.  looking into it now

**Comment by WuTheFWasThat** [comment]
well, i ended up self-hosting... switched all the links to https://www.wuthejeff.com/vimflowy/.  Let me know if you run into issues!

**Comment by gezeta-id** [comment]
Just FYI: You didn't change the link in the description of the project (seen on the sidebar on Github). It still points to vimflowy.netlify.app

**Comment by josephtannenbaum** [comment]
Thanks WuTheFWasThat! I was foolishly using the demo with local storage in my day-to-day; here's how I recovered using Chrome console. 1. In the https://vimflowy.netlify.app/ tab:

```js
copy(JSON.stringify(localStorage))
// your clipboard now has your data
```

2. Then in the new app's tab:

```js
foobar = // paste from your clipboard here and press enter
Object.keys(foobar).forEach(function (k) {
  localStorage.setItem(k, foobar[k]);
});
// then refresh the page!
```

I will be using my shiny new self-hosted Vimflowy from now on 🤦

**Comment by WuTheFWasThat** [comment]
i'm sure others are doing the same, so thanks for the public service!
