### ISSUE TITLE
Support for multi-line visual select

### ISSUE THREAD

**Issue by joboyx** [WuTheFWasThat/vimflowy#367]
Please support multiline visual select like this in VIM.

![image](https://user-images.githubusercontent.com/920888/105818219-98c90500-5ff1-11eb-8680-c6fdad3ffd68.png)

Actual Behavior:
* hit `v`
* hit `j` or `k`, it does nothing

![image](https://user-images.githubusercontent.com/920888/105818314-b8f8c400-5ff1-11eb-834c-d17b984a09b1.png)

**Comment by WuTheFWasThat** [comment]
yeah, multi-line visual mode behavior is tricky to define.  you can enter block visual with `V` instead.

**Comment by joboyx** [comment]
Oh, didn't know there's a multi-line visual mode -- `V`

I learned a new command for Vim again. Thanks.

You can close this.
