### ISSUE TITLE
make delete work for multiline case

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#37]

**Comment by vanceza** [comment]
Not sure what this is about.

Currently visual-mode multi-line delete works (but doesn't highlight) and something like 'd3d' works fine.

**Comment by WuTheFWasThat** [comment]
in vim, in visual mode, you can highlight contiguous selections even if it  contains parts of lines - it's not clear i should support such behavior, though, so i'll close the issue
