### ISSUE TITLE
Firebase Not Working

### ISSUE THREAD

**Issue by joboyx** [WuTheFWasThat/vimflowy#370]
![image](https://user-images.githubusercontent.com/920888/109664303-f67bde80-7ba7-11eb-9f28-40dc45ce8c18.png)

- I've setup a new project in firebase
- initialized firestore and added rules
- created user via email/password
- change data source in settings and input firebase keys/id and email/password
- but there's an error in console saying it can't reach firestore

Is it possible that you're using the old URL/protocol for Firestore -- firebaseio.com?

**Comment by WuTheFWasThat** [comment]
it's supposed to be realtime database, not firestore

**Comment by joboyx** [comment]
Thanks!

I was able to make it work now.

**Just some notes:**
* the hyperlink here is broken:
  ![image](https://user-images.githubusercontent.com/920888/109816508-c8f86900-7c6b-11eb-9cc6-fa2f69912b58.png)
* Would be great to mention "Realtime Database" here since there's already 2 types of DB in Firebase, other is Firestore. But yeah, if you follow the links you provided, it will redirect to Realtime Database page, so that's my bad.
  > https://github.com/WuTheFWasThat/vimflowy/blob/master/docs/storage/Firebase.md
* Lastly, would be great to mention that the "Firebase ID" mentioned here is the "Realtime Database URL" indicated in Realtime Database page. Like so -- `${projectId}-default-rtdb`
  ![image](https://user-images.githubusercontent.com/920888/109816908-3d330c80-7c6c-11eb-91f1-17c002ffafa7.png)
  ![image](https://user-images.githubusercontent.com/920888/109817070-70759b80-7c6c-11eb-8c20-688757497a10.png)

Nevertheless, all good! Awesome work! 🤩 

You can close this, if you want.

**Comment by joboyx** [comment]
One more thing I did, when I used the default Database Rules you provided, Firebase notified that it was not secure, since any user that can authenticate would be able to access your database. So fix for that is to do something like this:

![image](https://user-images.githubusercontent.com/920888/109817971-78820b00-7c6d-11eb-8903-ebbd48eac582.png)

And you can get your UID here:
![image](https://user-images.githubusercontent.com/920888/109818155-a7987c80-7c6d-11eb-9b3b-1f047dc6c481.png)

**Comment by WuTheFWasThat** [comment]
thank you!! updated docs :)
