### ISSUE TITLE
Sequence: keycombo characters

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#4]
`i` followed by `ctrl+r` inserts the literal `ctrl+r` as though it were a character. It should probably insert nothing instead.

**Comment by WuTheFWasThat** [comment]
yeah, right now everything that falls under "else" gets inserted.  not sure the right way to handle this - possibly just check the length of the thing being inserted?  that feels like a hack but i think has the right behavior

**Comment by vanceza** [comment]
Good enough. If I notice another problem case, we can re-open this.

**Comment by vanceza** [comment]
Oh, that's length in characters and not bytes, right?

**Comment by WuTheFWasThat** [comment]
yeah in characters
