### ISSUE TITLE
git hook to automatically push to vimflowy.bitballoon.com

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#41]

**Comment by WuTheFWasThat** [comment]
i have a script that does it, git hook is not necessarily a good idea anyways

**Comment by PeetrP** [comment]
WuTheFWasThat, would you share that script with us please?

**Comment by WuTheFWasThat** [comment]
it's wasn't much. see the bottom of this file:  https://github.com/WuTheFWasThat/vimflowy/blob/9a4e9cf643f757d82e20f561e7db457630de1f6b/build.sh

I ended up switching to pancake.io, so now i simply move the built assets into a dropbox folder for deployment
