### ISSUE TITLE
https://www.wuthejeff.com/vimflowy is down

### ISSUE THREAD

**Issue by joboyx** [WuTheFWasThat/vimflowy#415]
Any reason why the site is down? Even the main domain is down. But the domain is still registered.

Will this return?

Thanks for this awesome app 🫶

**Comment by WuTheFWasThat** [comment]
uh oh, will look into it!

**Comment by WuTheFWasThat** [comment]
hmm it works for me:

https://www.wuthejeff.com/vimflowy/#

**Comment by joboyx** [comment]
Looks like it was an SSL error on my side. Probably ISP or VPN related. When I reported I was connected to wifi. Then when I switched to mobile I was able to load the page. When I went back to wifi, I can now access it just fine.

Sorry for this. Closing this now.
