### ISSUE TITLE
italic, bold, font size

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#47]

**Comment by vanceza** [comment]
I'd rather just not have this

**Comment by WuTheFWasThat** [comment]
too late :/

**Comment by vanceza** [comment]
Can you not use 'meta' here? Using only two [non-shift] modifier keys is standard when you're going cross-OS.

**Comment by WuTheFWasThat** [comment]
yeah i'll change it
