### ISSUE TITLE
switch to iced coffeescript

### ISSUE THREAD

**Issue by WuTheFWasThat** [WuTheFWasThat/vimflowy#49]

**Comment by vanceza** [comment]
Before deciding on this, do you understand promises, which are sort of the standard solution (even if they're a little clunkier)?

**Comment by WuTheFWasThat** [comment]
yeah, but iced is nicer.  honestly, i'm pretty afraid of ever having to do an asynchronous storage layer.  it's going to cause massive rewrite, i think...  

for now, there's not much need for either solution, but i do like iced coffeescript

**Comment by vanceza** [comment]
I don't like adding additional layers of learning / debugging and prefer to go with the standard solution wherever possible.
50% of my time today was already spent trying to debug cryptic coffeescript compilation errors with no file or line numbers, so I'm unenthusiastic...

**Comment by WuTheFWasThat** [comment]
hm - i don't generally have issues with that in this particular case (coffeescript), but I do hate those kind of time sinks.  i don't have a strong opinion on this right now, so we can delay any decision until the need arises.  promises are fine and i don't have a good idea how nice iced coffeescript actually ends up being

FWIW i tend to be somewhat enthusiastic about newer, less well-tested stuff, heh.  (I briefly considered migrating the entire project to elm-lang a month ago, before deciding i'd already done too much work)

**Comment by vanceza** [comment]
Yeah, I definitely do that kind of stuff on personal projects, but I think there's a different set of considerations when working with more than one person and I hope you'll apply here
