### ISSUE TITLE
Default workflowy

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#50]
1. Check out master
2. Delete all localstorage
3. Refresh

I see two copies of the intial data, with two cursors.

**Comment by WuTheFWasThat** [comment]
how are you deleting all localstorage?  i still can't reproduce this.

try going to localhost:8080/otherdocument - does it still happen?

**Comment by vanceza** [comment]
I'm going into the 'resources' debug tab in developer mode. 

It also happens in both an incognito window and at localhost:8080/otherdocument.

**Comment by vanceza** [comment]
http://imgur.com/UkrmAQ1

**Comment by vanceza** [comment]
I believe create_view is being called twice (checked by printing from console.log) but I can only get the chrome debugger to stop there once.

**Comment by WuTheFWasThat** [comment]
that's so odd if true... the only thing i can think of is a bookmarklet, or something like that

there are only 3 places create_view gets called from (all in separate branches of an if else chain).  can you tell which of those is happening?

**Comment by vanceza** [comment]
The `if chrome?.storage?.sync` branch for both.

**Comment by vanceza** [comment]
Aha. both 'index.js' and a compiled 'app.js' were being included. Will fix.

**Comment by WuTheFWasThat** [comment]
update: apparently this randomly went away

closing for now as not reproducible
