### ISSUE TITLE
Flickering links distracting

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#63]
The bullet names at the top of the screen are clickable links in normal mode, but not in insert mode. Their color changes, I assume to indicate this. I find these color changes a bit distracting when there is a lot of text at the top of the screen. It might be worth tweaking the UI or providing an option to disable or something.

**Comment by za3k** [comment]
Okay, I think this is intended behavior (you can't navigate in insert mode by design), but Jeff suggests what should really want is the ability to do custom styling.
