### ISSUE TITLE
opening multiple documents in bitballoon

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#64]
I don't know any way to use multiple documents in bitballoon, and I'm a bit scared about opening several instances of the same document in different tabs (perhaps irrationally).

**Comment by WuTheFWasThat** [comment]
it warns you now if you're writing to a second tab

**Comment by paulfchristiano** [comment]
(my goal is to be able to have 2 panes open looking at different things; read only tabs or opening disjoint parts of the document in different tabs could also work, I didn't realize the disjoint tabs approach was impossible now)

**Comment by WuTheFWasThat** [comment]
it's possible, i'm just showing the dialogue very aggressively.  is it too much?

**Comment by WuTheFWasThat** [comment]
not clear what to do about this
