### ISSUE TITLE
special treatment for pasting once?

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#65]
I sometimes use dd + p to effectively move a bullet. But (1) copying is slow when the tree is large, (2) I'm hesitant to do this because of concerns about losing data if there is a crash while moving, (3) if future features (aliasing, or plugins like time tracking) depend on the identity of bullets then it would be nice if the first paste inherited the identity of the original node.

It would be nice to do one of: (1) have a separate hotkey for some kind of "cut and paste once" option, that just moves the node rather than cutting it, or (2) only allow pasting once from a deleted tree (I'm totally fine having to copy explicitly if I want to make copies), (3) treat the first paste as a special move operation.

**Comment by WuTheFWasThat** [comment]
i've changed the behavior to only allow one paste, always
