### ISSUE TITLE
Undo + view switch

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#7]
Insert: `A enter tab B enter tab C`
`alt+l` (zooms into `Home > A > B`)
`u` (un-zooms to `Home` AND undoes insert)
`ctrl+r` (error trying to zoom back in)

**Comment by WuTheFWasThat** [comment]
good catch.  I don't have time to fix this tonight.  if you fix it, please add a test case that fails, fix, then make sure it passes!

**Comment by WuTheFWasThat** [comment]
BTW, `npm test` to run tests.  they're all in tests.coffee and it should be straightforward to write them

**Comment by WuTheFWasThat** [comment]
actually, I don't see any error.  the intended behavior isn't to treat zooms themselves as something that is undoable-redoable, they're just a context in which undoable-redoable things can happen.  if you do another action after zooming in, then redoing that action will zoom

maybe this is weird behavior, and should be fixed?  but there's no real bug, as far as i can discern

**Comment by vanceza** [comment]
There's an error in the javascript console and I think it breaks undo/redo until page refresh maybe.
Will fix though sure, I wrote this before I could fix things :)

**Comment by WuTheFWasThat** [comment]
okay.  i couldn't reproduce at the time - might've been fixed in git repo but not in vimflowy.bitballoon?  fix very much appreciated if it's indeed broken though!

**Comment by WuTheFWasThat** [comment]
@vanceza was this ever resolved?

**Comment by vanceza** [comment]
It no longer throws an an error, but redo doesn't zoom in either, not sure if this is correct.
