### ISSUE TITLE
Italic/bold are broken

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#70]
Strikethrough seems to still work. May have something to do with keybinding conflicts, unsure yet.

**Comment by vanceza** [comment]
Note: Display of italic/bold works, it's only inserting them that doesn't. Tested on 'aliasing' only.

**Comment by WuTheFWasThat** [comment]
works for me on master - i think maybe you're confused by the fact that it's 

Ctrl+Shift+B... sorry, the display is terrible.  should fix, that's an issue in of itself

**Comment by vanceza** [comment]
Yeah, I think that was exactly it. Not sure about display vs convention, a bit of both. I think the shortcuts should be Ctrl-i and Ctrl-b to match other text editing software.
