### ISSUE TITLE
Incompatibility between master and aliasing

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#72]
If I create a document in master then use the same localstorage on aliasing, I get a mostly blank screen and the error:

TypeError: row.crumbs is undefined
data.js line 217 (in getParent).

**Comment by vanceza** [comment]
This is a known bug and won't be fixed because vimflowy doesn't really have users yet.

To work-around lack of data migration between versions:

1. Export your data
2. Delete your local storage for workflowy
3. Switch to the new version
4. Import your data
