### ISSUE TITLE
Visual line mode does not show highlight in aliasing

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#73]
Visual line mode does not show the highlight.

**Comment by vanceza** [comment]
Fixed by https://github.com/WuTheFWasThat/vimflowy/commit/08350052f5ac9952966e434041c9ccfbfeed7f02

**Comment by paulfchristiano** [comment]
I don't see highlighting on clones (even when only one of them is visible) in 2ee92fe8083f8896686f42c97f94ca281b1ae1de

**Comment by vanceza** [comment]
Refresh. Also, the highlighting is very subtle, which theme are you on?

**Comment by paulfchristiano** [comment]
This is the visual line highlighting, which is very much not subtle :) At first I thought visual line mode wasn't working, but it does work, it's just impossible to tell what is selected.

Attached a screen shot.

![screen shot 2015-10-19 at 4 05 50 pm](https://cloud.githubusercontent.com/assets/810371/10593788/643daef4-767b-11e5-8b40-84a39ac6e1db.png)

**Comment by paulfchristiano** [comment]
I guess it's just that the new highlight covers up the visual line highlight---unrelated to the previous bug that made the highlighting not appear

**Comment by vanceza** [comment]
Oh, I simultaneously added highlighting to all clones to indicate they were clones, so I misinterpreted your comment.

**Comment by vanceza** [comment]
Fixed by commit 7e00ca88fbfd96bd1e3c477bce9b5ffdc64bc64d
