### ISSUE TITLE
Marks, search do not display in aliasing

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#75]
The mark boxes don't show for me when editing, though if I type mmarkname<enter> it actually adds the mark.

Similarly, I can't see the search results or what I'm typing when I search. But the search works fine.

(All of my bug reports are from running commit 3537e812b3e9efea56f91e1afe4ab0ec2e3c5472 locally. some of them, like this one, seem to be OK on zak's copy at http://vimflowy.za3k.com/. Is there a more elegant way to point to a commit?)

**Comment by vanceza** [comment]
3537e81 is the ideal way to point to a commit, thanks. Use a local copy in place of my copy; I threw that up as a convenience but it's not synced to the latest version.

**Comment by vanceza** [comment]
c4fe793c8e5f82a691fea14ddfe65405b30e3155 may fix the issue with search results

**Comment by paulfchristiano** [comment]
For whatever reason, now fixed.
