### ISSUE TITLE
Add visual indicator for cloned rows

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#77]
Cloned rows should have some kind of highlight around them.

**Comment by vanceza** [comment]
Added highlights. I feel like they're fairly ugly and highlights weren't what we wanted so much as some mark to the left, etc. Jeff, better ideas?

**Comment by paulfchristiano** [comment]
This seems OK to me, though I'd prefer e.g. a slightly different appearance for the bullet.

**Comment by vanceza** [comment]
(Jeff, this is assigned to you to either okay as-is or improve the UI)

**Comment by WuTheFWasThat** [comment]
#89

**Comment by vanceza** [comment]
Closed as duplicate of #89
