### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#78]
I have a document with 4M words and about 400k bullets, I think about 20M characters. It consumes 1.4GB of memory, which seems like a lot. Importing also uses > 10x as much memory as the final document, which is enough to slow things down a lot. Not sure if this is worth doing anything about.

**Comment by paulfchristiano** [comment]
(The plain text file is 33MB.)

**Comment by paulfchristiano** [comment]
Huh, apparently even firefox has a localstorage limit (I guess at 16GB?) and so I can't import my workflowy document on aliasing.

(It's probably still OK, I think I can shrink it in a text editor.)

**Comment by vanceza** [comment]
If aliasing is using up significantly more localstorage, please open a separate issue for that.
