### ISSUE TITLE
Cloning bug

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#79]
Somehow an item ended up cloned without me noticing. It was not highlighted in blue. I noticed it was cloned when my cursor was mirrored. 

When I deleted one of the two, the other one got the clone highlighting. When I added a mark on the now-highlighted node, the app crashed, and now state cannot be loaded.

Here is the error message on document load (same error when the thing choked).

Error: Assertion error: No parent found for id: 186302
Expected false to be true

(on commit 2ee92fe8083f8896686f42c97f94ca281b1ae1de)

**Comment by paulfchristiano** [comment]
Sorry that I don't know how to reproduce this, your guess is as good as mine.

**Comment by paulfchristiano** [comment]
Is there some way to repair the state? This is maybe 30-60m of work, which isn't a huge deal but is pretty annoying. I don't know whether to expect more bugs of this kind, but without some way to recover from these errors I feel like I should probably run master to be safe.

Seems like it might be possible to repair the state by just attaching orphaned nodes to the root or something?

**Comment by vanceza** [comment]
As I've said, yes, you should not do important work in internal development branches.

I suspect this is a duplicate of #71, so I'm going to close it unless you can make a reproduction case. If you want to fix your internal state, please grab me on gchat.
