### ISSUE TITLE
Change 'viewRoot' should be an id again

### ISSUE THREAD

**Issue by vanceza** [WuTheFWasThat/vimflowy#81]
Change the version number if needed as well

**Comment by WuTheFWasThat** [comment]
i think it's actually correct as a row

**Comment by vanceza** [comment]
This refers to how it's supposed to be stored in localstorage only, was unclear

**Comment by WuTheFWasThat** [comment]
yeah, i do think lastViewRoot should be a row, though.  when i refresh the page, and i'm within a clone, i want to end up at the same path

**Comment by vanceza** [comment]
Would still prefer to be storing it as an array of IDs, right now deserialization fails

**Comment by WuTheFWasThat** [comment]
i fixed it though - take a look and see if it's okay, then close?

**Comment by vanceza** [comment]
Seems good
